const jwt = require('jsonwebtoken');

exports.verifyToken = async (req, res, next) => {
    // get token from header
    const token = req.get('Authorization');
    if (!token) {
        return next();
    }

    // verify token
    try {
        const decoded = jwt.verify(token, process.env.JWT_SECRET);
        req.user = decoded;
    } catch (err) {
        return next();
    }
    next();
};

exports.errorhandler = (err) => {
    // check if the error is generated by the server or request
    if(err.statusCode) {
        return {
            statusCode: err.statusCode,
            message: err.message,
            data: err.data
        };
    } else {
        console.log(err);
        return { 
            msg: 'Something went wrong we are working on it.' 
        }
    }
};