const sequelize = require('sequelize');

exports.verifyToken = async (req, res, next) => {
    // get token from header
    const token = req.get('Authorization');
    if (!token) {
        return next();
    }

    // verify token
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    req.user = decoded;
    next();
};

exports.errorhandler = (err, req, res, next) => {
    // check if the error is generated by the server or request
    if(err.statusCode) {
        res.status(err.statusCode).json({
            message: err.message,
            data: err.data
        });
    } else {
        console.error(err);
        res.status(500).json({ message: 'Something went wrong' });
    }
};